### ISSUE TITLE
node fail start

### ISSUE THREAD

**Issue by carl0shd** [EvenAR/node-simconnect#11]
Hello,

i have a problem when trying to start the example script, i have node 32bits.

node examples/nodejs/example.js

node-simconnect: Loading pre-built binary
internal/modules/cjs/loader.js:1208
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The application could not be started; The parallel configuration is not correct. Check the application event log or use the sxstrace.exe tool on the command line for more details.

\\?\test_simconnect\watt\simconnect\bin\win_ia32\node-simconnect.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1208:18)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:test_simconnect\watt\simconnect\index.js:16:22)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)

**Comment by carl0shd** [comment]
Problem solved, I needed to install simconnect 👍
