### ISSUE TITLE
Reading TITLE value crashes electron app

### ISSUE THREAD

**Issue by RobsonMi** [EvenAR/node-simconnect#34]
A simple read of TITLE value often crashes simconnect node module (according to Event Viewer).

Since removal of TITLE from array of retrieved values problems are gone. Any suggestions as to how I should debug actual cause of error and attempt a fix? I am moderately familiar with simconnect and C++ so I might be able to fix this. Just not sure how to setup debugging to break on problem. Instructions would be gold.

**Comment by EricLin0826** [comment]
same problem

**Comment by EvenAR** [comment]
@RobsonMi @EricLin0826, please check out the new version 3.x. The new version is javascript only and it should be more stable than 1.x.

**Comment by Pomax** [comment]
I think this might still be happening - I tried to pull `PLANE LATITUDE`, `PLANE LATITUDE`, and `TITLE`, which does not seem to pull the title properly:
```
import {
  open,
  Protocol,
  SimConnectDataType,
  SimConnectPeriod,
  SimConnectConstants,
} from "node-simconnect";

const POSITION_DATA = 1;
const REQUEST_ID_POSITION_DATA = 1;
const EVENT_ID_PAUSE = 1;

open("My app", Protocol.FSX_SP2)
  .then(function ({ recvOpen, handle }) {
    console.log("Connected to", recvOpen.applicationName);

    handle.addToDataDefinition(
      POSITION_DATA,
      "Plane Latitude",
      "degrees",
      SimConnectDataType.FLOAT64,
      0.0,
      SimConnectConstants.UNUSED
    );
    handle.addToDataDefinition(
      POSITION_DATA,
      "Plane Longitude",
      "degrees",
      SimConnectDataType.FLOAT64,
      0.0,
      SimConnectConstants.UNUSED
    );

    handle.addToDataDefinition(
      POSITION_DATA,
      "Title",
      "string",
      SimConnectDataType.STRING128,
      0.0,
      SimConnectConstants.UNUSED
    );

    handle.requestDataOnSimObject(
      REQUEST_ID_POSITION_DATA,
      POSITION_DATA,
      SimConnectConstants.OBJECT_ID_USER,
      SimConnectPeriod.SECOND,
      0,
      0,
      0,
      0
    );
    handle.subscribeToSystemEvent(EVENT_ID_PAUSE, "Pause");

    handle.on("event", function (recvEvent) {
      switch (recvEvent.eventID) {
        case EVENT_ID_PAUSE:
          console.log(recvEvent.data === 1 ? "Sim paused" : "Sim unpaused");
          break;
      }
    });

    handle.on("simObjectData", function (recvSimObjectData) {
      switch (recvSimObjectData.requestID) {
        case POSITION_DATA:
          console.log({
            latitude: recvSimObjectData.data.readFloat64(),
            longitude: recvSimObjectData.data.readFloat64(),
            title:  recvSimObjectData.data.readString128(),
          });
          break;
      }
    });
    handle.on("quit", function () {
      console.log("Quit");
    });
  })
  .catch(function (error) {
    console.log("Connection failed:", error);
  });
```

(So this is the mjs example with `Title` added)

This yields the following error in the console:

```
d:\temp>node repro.js
Connected to KittyHawk
d:\temp\node_modules\bytebuffer\dist\bytebuffer-node.js:1861
                throw RangeError("Illegal offset: 0 <= "+offset+" (+"+1+") <= "+this.buffer.length);
                ^

RangeError: Illegal offset: 0 <= 44 (+1) <= 44
    at ByteBuffer.module.exports.ByteBufferPrototype.readCString (d:\temp\node_modules\bytebuffer\dist\bytebuffer-node.js:1861:23)
    at makeString (d:\temp\node_modules\node-simconnect\dist\RawBuffer.js:150:24)
    at RawBuffer.readString128 (d:\temp\node_modules\node-simconnect\dist\RawBuffer.js:105:16)
    at SimConnectConnection.<anonymous> (file:///d:/temp/repro.js:69:44)
    at SimConnectConnection.emit (node:events:513:28)
    at SimConnectConnection.emit (d:\temp\node_modules\node-simconnect\dist\SimConnectConnection.js:78:22)
    at SimConnectConnection._handleMessage (d:\temp\node_modules\node-simconnect\dist\SimConnectConnection.js:1031:22)
    at SimConnectSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
```
