### ISSUE TITLE
"Title" causes a node-simconnect crash

### ISSUE THREAD

**Issue by Pomax** [EvenAR/node-simconnect#67]
It looks like there might be some lingering problems with the `TITLE` simvar, despite fixes in https://github.com/EvenAR/node-simconnect/issues/34:

I tried to pull `PLANE LATITUDE`, `PLANE LATITUDE`, and `TITLE`, by extending the  `aircraftPosition.mjs` sample, and that seems to error out in v3.3.0 when it tries to read the title:

```javascript
import {
  open,
  Protocol,
  SimConnectDataType,
  SimConnectPeriod,
  SimConnectConstants,
} from "node-simconnect";

const POSITION_DATA = 1;
const REQUEST_ID_POSITION_DATA = 1;
const EVENT_ID_PAUSE = 1;

open("My app", Protocol.FSX_SP2)
  .then(function ({ recvOpen, handle }) {
    console.log("Connected to", recvOpen.applicationName);

    handle.addToDataDefinition(
      POSITION_DATA,
      "Plane Latitude",
      "degrees",
      SimConnectDataType.FLOAT64,
      0.0,
      SimConnectConstants.UNUSED
    );
    handle.addToDataDefinition(
      POSITION_DATA,
      "Plane Longitude",
      "degrees",
      SimConnectDataType.FLOAT64,
      0.0,
      SimConnectConstants.UNUSED
    );


    // -----------------added-----------------------
    handle.addToDataDefinition(
      POSITION_DATA,
      "Title",
      "string",
      SimConnectDataType.STRING128,
      0.0,
      SimConnectConstants.UNUSED
    );
    // ----------------------------------------------

    handle.requestDataOnSimObject(
      REQUEST_ID_POSITION_DATA,
      POSITION_DATA,
      SimConnectConstants.OBJECT_ID_USER,
      SimConnectPeriod.SECOND,
      0,
      0,
      0,
      0
    );
    handle.subscribeToSystemEvent(EVENT_ID_PAUSE, "Pause");

    handle.on("event", function (recvEvent) {
      switch (recvEvent.eventID) {
        case EVENT_ID_PAUSE:
          console.log(recvEvent.data === 1 ? "Sim paused" : "Sim unpaused");
          break;
      }
    });

    handle.on("simObjectData", function (recvSimObjectData) {
      switch (recvSimObjectData.requestID) {
        case POSITION_DATA:
          console.log({
            latitude: recvSimObjectData.data.readFloat64(),
            longitude: recvSimObjectData.data.readFloat64(),

            // -----------------added-----------------------
            title:  recvSimObjectData.data.readString128(),
            // ----------------------------------------------

          });
          break;
      }
    });
    handle.on("quit", function () {
      console.log("Quit");
    });
  })
  .catch(function (error) {
    console.log("Connection failed:", error);
  });
```

This yields the following error in the console:

```
d:\temp>node repro.js
Connected to KittyHawk
d:\temp\node_modules\bytebuffer\dist\bytebuffer-node.js:1861
                throw RangeError("Illegal offset: 0 <= "+offset+" (+"+1+") <= "+this.buffer.length);
                ^

RangeError: Illegal offset: 0 <= 44 (+1) <= 44
    at ByteBuffer.module.exports.ByteBufferPrototype.readCString (d:\temp\node_modules\bytebuffer\dist\bytebuffer-node.js:1861:23)
    at makeString (d:\temp\node_modules\node-simconnect\dist\RawBuffer.js:150:24)
    at RawBuffer.readString128 (d:\temp\node_modules\node-simconnect\dist\RawBuffer.js:105:16)
    at SimConnectConnection.<anonymous> (file:///d:/temp/repro.js:69:44)
    at SimConnectConnection.emit (node:events:513:28)
    at SimConnectConnection.emit (d:\temp\node_modules\node-simconnect\dist\SimConnectConnection.js:78:22)
    at SimConnectConnection._handleMessage (d:\temp\node_modules\node-simconnect\dist\SimConnectConnection.js:1031:22)
    at SimConnectSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
```

Just to double check I tried this with uppercase simvar names, too, but that has the same result.

**Comment by RobsonMi** [comment]
Hi, have you tried with `readStringV()` as per samples?
https://github.com/EvenAR/node-simconnect/blob/master/samples/typescript/aircraftInformation.ts

**Comment by Pomax** [comment]
I had not, because the MSFS Simvar docs suggest it's a "String (max 128 chars)". Are there docs somewhere that explain when node-simconnect wants a stringv instead?

**Comment by Pomax** [comment]
Updated the code to StringV, looks like the same problem:

```javascript
import {
  open,
  Protocol,
  SimConnectDataType,
  SimConnectPeriod,
  SimConnectConstants,
} from "node-simconnect";

const POSITION_DATA = 1;
const REQUEST_ID_POSITION_DATA = 1;
const EVENT_ID_PAUSE = 1;

open("My app", Protocol.FSX_SP2)
  .then(function ({ recvOpen, handle }) {
    console.log("Connected to", recvOpen.applicationName);

    handle.addToDataDefinition(
      POSITION_DATA,
      "PLANE LATITUDE",
      "degrees",
      SimConnectDataType.FLOAT64,
      0.0,
      SimConnectConstants.UNUSED
    );
    handle.addToDataDefinition(
      POSITION_DATA,
      "PLANE LONGITUDE",
      "degrees",
      SimConnectDataType.FLOAT64,
      0.0,
      SimConnectConstants.UNUSED
    );

    handle.addToDataDefinition(
      POSITION_DATA,
      "TITLE",
      "string",
      SimConnectDataType.STRINGV,
      0.0,
      SimConnectConstants.UNUSED
    );

    handle.requestDataOnSimObject(
      REQUEST_ID_POSITION_DATA,
      POSITION_DATA,
      SimConnectConstants.OBJECT_ID_USER,
      SimConnectPeriod.SECOND,
      0,
      0,
      0,
      0
    );
    handle.subscribeToSystemEvent(EVENT_ID_PAUSE, "Pause");

    handle.on("event", function (recvEvent) {
      switch (recvEvent.eventID) {
        case EVENT_ID_PAUSE:
          console.log(recvEvent.data === 1 ? "Sim paused" : "Sim unpaused");
          break;
      }
    });

    handle.on("simObjectData", function (recvSimObjectData) {
      switch (recvSimObjectData.requestID) {
        case POSITION_DATA:
          console.log({
            latitude: recvSimObjectData.data.readFloat64(),
            longitude: recvSimObjectData.data.readFloat64(),
            title:  recvSimObjectData.data.readStringV(),
          });
          break;
      }
    });
    handle.on("quit", function () {
      console.log("Quit");
    });
  })
  .catch(function (error) {
    console.log("Connection failed:", error);
  });
```
Error:
```
D:\temp>node repro.js
Connected to KittyHawk
D:\temp\node_modules\bytebuffer\dist\bytebuffer-node.js:1861
                throw RangeError("Illegal offset: 0 <= "+offset+" (+"+1+") <= "+this.buffer.length);
                ^

RangeError: Illegal offset: 0 <= 44 (+1) <= 44
    at ByteBuffer.module.exports.ByteBufferPrototype.readCString (D:\temp\node_modules\bytebuffer\dist\bytebuffer-node.js:1861:23)
    at makeString (D:\temp\node_modules\node-simconnect\dist\RawBuffer.js:150:24)
    at RawBuffer.readStringV (D:\temp\node_modules\node-simconnect\dist\RawBuffer.js:139:16)
    at SimConnectConnection.<anonymous> (file:///D:/temp/repro.js:69:44)
    at SimConnectConnection.emit (node:events:513:28)
    at SimConnectConnection.emit (D:\temp\node_modules\node-simconnect\dist\SimConnectConnection.js:78:22)
    at SimConnectConnection._handleMessage (D:\temp\node_modules\node-simconnect\dist\SimConnectConnection.js:1031:22)
    at SimConnectSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
```

**Comment by Pomax** [comment]
If I set it to `null`, the script seems to just "hang", where it logs `Connected to KittyHawk` and then doesn't generate any output until I kill node. Using both `"NULL"` or `"null"` causes the same crash as above.

**Comment by EvenAR** [comment]
Hmm, ok. There could be a SimConnect exception happening. Do you get anything if you add this?
```js
handle.on("exception", function (ex) {
  console.log(ex);
});
```

**Comment by Pomax** [comment]
ooh, you're right: `RecvException { exception: 28, sendId: 4, index: 2 }`

**Comment by Pomax** [comment]
Oh! So I change the STRINGV back to STRING128, but with `null`, it works!

```
    handle.addToDataDefinition(
      POSITION_DATA,
      "TITLE",
      null,
      SimConnectDataType.STRING128,
      0,
      SimConnectConstants.UNUSED
    );
```

**Comment by EvenAR** [comment]
My only guess is that it refers to variable length strings (STRINGV)

**Comment by Pomax** [comment]
@EvenAR @RobsonMi thanks for the (ridiculously fast! =D) help!

**Comment by EvenAR** [comment]
You're welcome!

I just tested the sample, and it does work as expected (at least on my machine). However, changing `SimConnectPeriod.ONCE` to something else (like `SimConnectPeriod.SECOND`) gives me the same exception (28). It looks like `STRINGV` can only be used with `SimConnectPeriod.ONCE`. 

I think you can close this issue. I will update the sample to use `STRING32` and `STRING128` right away to avoid future confusion 😃
